name: Deploy Node Application

on: 
  workflow_dispatch:     # ✅ allows manual "Run workflow" trigger
  push:
    branches:
      - mern-ec2-docker-ssl   # ✅ your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t aryanraj0001/chat-app .

      - name: Publish Image to Docker Hub
        run: docker push aryanraj0001/chat-app:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Image from Docker Hub
        run: docker pull aryanraj0001/chat-app:latest

      - name: Delete Old Container
        run: docker rm -f chat-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 \
          --name chat-app-container \
          -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
          aryanraj0001/chat-app:latest
