
name: Deploy Backend Chat App on EC2

on:
  workflow_dispatch:    # ✅ manual trigger
  push:
    branches:
      - main           # deploy only from main branch

jobs:
  backend-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # ------------------------------
      # CHECKOUT CODE
      # ------------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------------------
      # SETUP NODE
      # ------------------------------
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      # ------------------------------
      # INSTALL BACKEND DEPENDENCIES
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      # ------------------------------
      # CREATE BACKEND .ENV
      # ------------------------------
      - name: Create backend .env file
        working-directory: ./server
        run: |
          touch .env
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      # ------------------------------
      # START BACKEND WITH PM2
      # ------------------------------
      - name: Start backend with PM2
        working-directory: ./server
        run: |
          # install PM2 if missing
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          # restart backend if exists, else start
          pm2 restart backend || pm2 start server.js --name backend --update-env
          pm2 save

      # ------------------------------
      # DONE
      # ------------------------------
      - name: Deployment complete
        run: echo "🚀 Backend successfully deployed on EC2!"
