name: Deploy Fullstack Chat App on EC2

on:
  push:
    branches:
      - main  # Run only when code is pushed to main branch

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # ------------------------------
      # CHECKOUT CODE
      # ------------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------------------
      # SETUP NODE
      # ------------------------------
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      # ------------------------------
      # BACKEND SETUP
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Create backend .env file
        working-directory: ./server
        run: |
          touch .env
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Start backend with PM2
        working-directory: ./server
        run: |
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          pm2 restart backend || pm2 start server.js --name backend --update-env
          pm2 save

      # ------------------------------
      # FRONTEND SETUP
      # ------------------------------
      - name: Clean npm cache & remove existing dependencies
        working-directory: ./client
        run: |
          rm -rf node_modules package-lock.json dist
          npm cache clean --force

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Create frontend .env file
        working-directory: ./client
        run: |
          touch .env
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      # ------------------------------
      # DEPLOY FRONTEND TO NGINX
      # ------------------------------
      - name: Deploy frontend to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r ./client/dist/* /var/www/html/
          sudo systemctl restart nginx

      # ------------------------------
      # DONE
      # ------------------------------
      - name: Deployment complete
        run: echo "🚀 Chat App successfully deployed on EC2!"
