name: Deploy Fullstack App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # ------------------------------
      # 1️⃣ Checkout repository
      # ------------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------------------
      # 2️⃣ Setup Node.js
      # ------------------------------
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      # ------------------------------
      # 3️⃣ Backend Setup
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Create backend .env file
        working-directory: ./server
        run: |
          touch .env
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Start backend with PM2
        working-directory: ./server
        run: |
          # Use correct PM2 path; adjust if needed
          /home/ubuntu/.nvm/versions/node/v22.16.0/bin/pm2 restart backend || \
          /home/ubuntu/.nvm/versions/node/v22.16.0/bin/pm2 start index.js --name backend

      # ------------------------------
      # 4️⃣ Frontend Setup
      # ------------------------------
      - name: Clean npm cache & remove old dependencies
        working-directory: ./client
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Create frontend .env file
        working-directory: ./client
        run: |
          touch .env
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: ./client
        run: |
          # Increase memory if build fails on EC2
          export NODE_OPTIONS=--max_old_space_size=2048
          npm run build

      # ------------------------------
      # 5️⃣ Deploy frontend to Nginx
      # ------------------------------
      - name: Deploy frontend
        run: |
          # Remove old files
          sudo rm -rf /var/www/html/*
          # Copy build files (React default build folder is 'build')
          sudo cp -r ./client/build/* /var/www/html/
